### PR TITLE
fix cv output (ad5686) by disabling DMA4 autobuffer

### PR DESCRIPTION
**Pull request by catfact**
also clean a lot of dead code from bfin_lib

### CODE REVIEW

**Comment by boqs** [comment]
Just recompiled & loaded this code onto my aleph...

using waves:

enc1 -> cv0
enc2 -> cv1
enc3 -> cv0slew
enc4 -> cv1slew

I hooked this up to my modular & did  a listening test where cv0 controls pitch, cv1 controls amplitude. everything seems smooth & functional using that test.  don't have a scope to really zone in on the described bug.

**Comment by catfact** [comment]
uhoh!

*maybe* the new scheme requires like, one more cycle per CV update (it has to explicitly restart the DMA channel.) other than that i can't think of a reason right now

**Comment by boqs** [comment]
hmmm are you observing recreatable bugs?

Thought I saw some intermittent weirdness at one point but could be nothing, or might just be related to long slew times.  Couldn't see anything wrong at all using fast slews, and saw no weirdness when also using this monkey-patch to filter_1p (this is the slew algorithm from ricks_tricks):

```c
fract32 filter_1p_lo_next(filter_1p_lo* f) {
  fract32 difference = sub_fr1x32(f->y, f->x);
  fract32 radix = norm_fr1x32(difference);
  f->y = add_fr1x32( f->x,
		     shr_fr1x32(mult_fr1x32x32(f->c,
					       shl_fr1x32(difference, radix)),
				radix));
  return f->y;
}
```

**Comment by catfact** [comment]
ach, you know, i am seeing some weird stuff actually. using `waves`, and using a pair of METROs to toggle cv0 and cv1 with slew. the outputs seem to get "stuck" at random points.

with cv0 on a slow toggle, long slew, and cv1 on a faster toggle, faster slew, cv0 seems to "want" to get "stuck" whenever cv1 changes.

yeech. 

however, if i disable slew processing in `waves`, things look as expected. yea, unto the 5ms metro bang. (there is a tiny bit of overshoot + ringing on every rising edge, which is a little unexpected but not wildly so.)

so, i dunno.. something wrong with slew hold calculation? some insiduous memory-smashing bug in waves? (looking through the history / dead code, i'm seeing that i ran into trouble when trying to refactor the slew processors in waves to be more efficient... maybe related?)

oh btw, i am limited to scope for looking at this. and in fact a weird, chinese digital travel scope with a badly-translated interactive manual. its not impossible that i just have the triggering set up all wrong...

**Comment by boqs** [comment]
> ach, you know, i am seeing some weird stuff actually. using waves, and using a pair of METROs to toggle cv0 and cv1 with slew. the outputs seem to get "stuck" at random points.

yeah that sounds like what I *thought* I was hearing!  (i rigged amplitude, pitch & a filter to test by ear)...  Gonna try a cv-only module to rule out a 'running out of cpu cycles' kind of bug.

**Comment by catfact** [comment]
ok, yea, this is some problem with the logic of "syncing" the slew filters. somehow when one channel is deemed to be "synced" it is freezing the update of other channels. (?) bypassing this test:
https://github.com/monome/aleph/blob/dev/modules/waves/waves.c#L442

improves the behavior and doesn't leave any other oddities that i can see right now.

the "sync" mechanism is pretty dumb anyways, probably one of those optimizations that doesn't help; it's constantly doing comparisons for questionable and inconsistent processing savings, and evidently is causing glitches to boot.

this needs more attention but i'll leave the PR open for now? i don't think it's really a directly related issue. (to the ad5686 output itself, that is)

**Comment by boqs** [comment]
> the "sync" mechanism is pretty dumb anyways, probably one of those optimizations that doesn't help; it's constantly doing comparisons for questionable and inconsistent processing savings, and evidently is causing glitches to boot.

yeah this kind of optimisation is a recipe for intermittent bugs!  I will tweak a little more, see if I can get waves/lines CV looking solid end-to-end, then open another PR building on your commits ( already merged this into my dev) once CV is definitively fixed in these 2 modules we can merge both

**Comment by catfact** [comment]
awesome! agree, this slew is stupid, yours is better. 

so i'll just merge this PR and then slew fixings on top yeah?

**Pull request merged**
