### PR TITLE
prgm sample transfer

### PR DESCRIPTION
**Pull request by prgmsoftware**
this are the changes made to the prgm app that were made to handle samples with increased transfer speed. changes are a bit scattered but it was just that it was small changes here and there that was needed to get the better speed. some things would need to be made into operators or similar for this to work well with BEES, and it will probably not get past a make command at this state..

### CODE REVIEW

**Comment by prgmsoftware** [comment]
oh, I forgot one thing..

in aleph/avr32/src/init.c/init_bfin_resources(), changed the .trans_delay to 1 (from 20)

if these ideas seem to be worth an effort and seems OK I can happily assist in adapting this for BEES more properly! note, sample transfer is about 300 kb/s with these changes which is ok but I think it can be improved further still.

some things not clear yet..
- when loading samples should be initiated, in the BEES world this could be upon loading a module or the BEES app, since all modules will not need/support samples, maybe it should be requested by the module
- all modules could share a common sample library/folder, or they could be separate, currently using data/module/samples as search path

I have not looked at sample/file management at all, samples are just loaded in order of date/time when copied to the card, I guess this is how the files are ordered by default in the file system.

finally, this feature should definitely launch with a custom Aleph/BEES sample library :)

//Test2

**Comment by boqs** [comment]
Thanks so much for this!  I will have a look in the next few days...

I was thinking the mininum viable option to get BEES transferring audio to/fro the blackfin would be:

- add a new 'audio buffer' page to BEES menus
- it would have a list of raw pcm files (independent of modules) which can be loaded or saved from SDRAM. (possibly concatenated samples)
- If you use the same name as the scene, it could autoload

And definitely agree about the sample library. (though I'm such a stranger to sampling I couldn't help much with such a thing)

**Comment by prgmsoftware** [comment]
I dig the idea of an audio buffer page, that feels like a good starting point, I can start working on that (as I find the time here and there).

**Comment by Yankow2** [comment]
This is splendid. I will happily contribute to the sample library if you decide to go for a Bees version of prgm.

**Comment by catfact** [comment]
i'm gonna merge this but let's keep an eye on PDCA timing for scene storage &c

**Comment by prgmsoftware** [comment]
wait, I'm not sure what's happening now, this PR was meant as a basis for discussion, it's not going to work in this state. I'm will try to put together a working basic setup with a BEES audio buffer page as a first step, let me get back when this is ready!

**Comment by catfact** [comment]
oh ok I'll revert

**Comment by catfact** [comment]
sorry about that. i only glanced at the pdca changes and thought it was something we could play with 

i'll make a new feature branch from your dev, open new PR with big 'do not merge' sign for my self :)

**Comment by catfact** [comment]
ok so i'l leave that there, unfortunately it wasn't easy to get your commits back. 

maybe this PR is still ok place for discussion, and `sample-transfer` feature branch can be where actual, working incremental changes are added (e.g. PDCA timing and SPI protocol additions.) first step probably being reverting or at least macro-ing out the currently broken bits. (or just make new one of course, as you like)

**Pull request merged**
