### PR TITLE
merge skektek/libavr32 & other changes

### PR DESCRIPTION
**Pull request by boqs**
All changes from skektek 'non-release' & @catfact's libavr32 branch have been rolled together into one.  I've been running & testing quite a bit - no known regressions, help with testing would be much appreciated!

new features:
- new op: midi_prog
- new grid ops: op_mem0d, op_mem1d, op_mem2d, grid_raw, life_raw, iter
- new poly op to handle note priority of mono & poly synths
- new 'harry' op to generate 'Hz scaler' values for tonality diamond a la harry partch
- new maginc op to 'magically increment' the DSP param or BEES input it points to
- new kria op
- view operator outputs on play screen
- pickle state of all grid ops to scene
- BEES emulator for puredata allows operator development under PD
- DSP emulators for puredata & linux/jack
- ladder filter DSP primitives
- 'varilines' module (varispeed lines)
- 'acid' two voice synth/drum module
- 'fmsynth' monophonic oversampling ADSR FM synth module with analogue feedback routing
- 'label' DSP param scaler which permits textual display of 'patch points'
- assorted UI improvements

memorable bugfixes:
- fixed preset system including arbitrary op deletion/insertion
- midi input fixed by libavr32 merge (previously buggy 'firehosing')
- make output of random op more random
- fix grid op focus-swapping
- optimised waves to fix crackling on param changes
- small whitewhale, op_step bugs

### CODE REVIEW

**Comment by catfact** [comment]
this is extremely exciting, thanks

im just gonna list things that aren't compiling as i come across them. not to say they need to be fixed in this PR (or indeed at alll, some targets are probably obsolete / unneeded)

not compiling:

## apps
- picolisp app (needs update for lilbavr32)

## modules
- mix module (linker script is weirdly incomplete)
- pitchtoy: 
```
../../dsp/pitch_shift.c: In function ‘pitchShift_next’:
../../dsp/pitch_shift.c:42: error: ‘pitchShift’ has no member named ‘pitchDetector’
&c
```
- ~~varilines: missing linker script~~

## utils
- `avr32_boot` (bootloader.) that's not so great! (needs update for libavr32)
- `avr32_test` (basic hardware test app.) needs libavr32 update
- `i2c-repeater` (avr8 TWI tester). some weird warnings. maybe just delete this
- `bfin_pd` - i forget how this works.

there's other crud in the utils that should probably be clean out.

## param scaling

do i need to rebuild scaler data?

**Comment by boqs** [comment]
> do i need to rebuild scaler data?

I think not!  IIRC the only scaler thing I touched was adding the label scaler type.  And that pulls it's label data from a .lab file

>pitchtoy:

yeah I need to get round to fixing that - going to expunge it from dev until I find the time to resurrect.  I mean grains is already a pretty capable 'pitchtoy', just needs some focussed patching work to make it musically useful...

> avr32_boot (bootloader.) that's not so great! (needs update for libavr32)
> avr32_test (basic hardware test app.) needs libavr32 update

dunno how to approach these & yes we should fix this before merge - if you can make some progress on it, I'll pull it right into boqs/dev

**Comment by catfact** [comment]
sure thing, i can probably do that and give you a patch. needs JTAG dongle to test...

**Comment by catfact** [comment]
fixed the aleph bootloader and opened a PR for the head of this PR  :/

can send you a patch if that's better

**Comment by catfact** [comment]
so i've been "testing" this in the sense of using bees quite a bit over the last week.

put together a performance exensively using varilines, kria + rawgrid switching focus.

came across some bugs/ quirky things with the grid, but no obvious regressions.

one thing though, is that all the new stuff does need a bit of documentation. tedious though it may be. i'm unclear enough about how some things work that i couldn't really test them (the MEM ops, acid) - for kria i had to look at the bottom row handler to understand how the modes are mapped (different from current ansible version.)

and once again, huge thanks to you for this update. varilines is great, glitchless waves is  very satsifying, and op insertion/deletion is super helpful!

**Review by catfact — APPROVED** [review]

**Comment by catfact** [comment]
@tehn if there's no objections i'll go ahead and merge this. i can then add my fixes to the bootloader and start in on some documentation before tagging v0.8.0 and bringing it into master

**Comment by tehn** [comment]
wonderful! go for it

**Pull request merged**
