### PR TITLE
bfin emulator bugs, new modules, assorted DSP inc softclip svf

### PR DESCRIPTION
**Pull request by ghost**
Nothing that should be controversial in here, apart from the changes to svf code.  Those could potentially affect @catfact's original modules and I admit haven't actually tested lines/waves/dsyn since making the changes but I believe old svf code was just not quite right.  I'll try and get some testing done tomorrow evening.  Maybe also ask for help with this on the forum...

This pull-request addresses bugs in bfin emu (see https://github.com/monome/aleph/issues/245)

I'm claiming svf changes address these three issues:

https://github.com/monome/aleph/issues/147
https://github.com/monome/aleph/issues/145
https://github.com/monome/aleph/issues/101

not actually bothering to over-sample the svf in monosynth module, ~6kHz upper limit is something I'll live with, seeing as it prob also makes this code run faster...  Original oversampled version should still work exactly as before, though the code was reordered a bit to make the built-in mixer optional...

oh and there are three new modules - all works in progress but hey...

### CODE REVIEW

**Comment by catfact** [comment]
hot damn. fantastic. i'm going to test the old modules about before merging, though i certainly don't forsee any issues having these changes on the dev branch.

**Comment by ghost** [comment]
note to self: don't forget to add the old svf wrapping rq functionality back in & add a dsyn param to flick this feature on/off for that module.

**Comment by catfact** [comment]
ehh, i don't think that's really necessary. i was being a bit facetious, surely better to have RQ parameter work as expected in all cases.

**Comment by ghost** [comment]
I really like the idea that this 'bug' is also a feature! (kinda like the frequency wrapping 'bug' on DX7 I read about somewhere)

It's 5 minutes work to make that change - no regressions for the sake of 'correctness'!  Look here:
https://github.com/rick-monster/aleph/blob/dev_rebased/dsp/filter_svf.c#L45-L89
2 completely arbitrary distortion flavours.  One more doesn't hurt...

**Comment by catfact** [comment]
added ricks_tricks to lines/dsyn makefiles, so they compile. sounds fine!

**Comment by catfact** [comment]
btw maybe worth pointing out that `waves` uses it's own sfv implementation, so it will not benefit. but waves needs work anyways... blech

**Comment by ghost** [comment]
Maybe I'll try firing waves up in linux emulator - I would bet anyone five bucks (canadian) it will _just work_ after removing any ifdefs from old portaudio wrapper...

**Comment by catfact** [comment]
the main problems IMO are kinda hardware-specific, i'd guess:
- glitches / drops samples every time a control change happens! really awful. optimization thing.
- truncation in multiply accumulator (i think?) means that tuning values get quantized in an unfortunate manner.

**Comment by ghost** [comment]
Explain more about the tuning values getting quantized in an unfortunate manner!  Maybe open an issue?  I had a minor epiphany how to do really long slews with the fract arithmetic primitives - maybe this technique helps:
https://github.com/monome/aleph/blob/dev/dsp/ricks_tricks.c#L310-L326
?

**Comment by catfact** [comment]
yechh, it's more icky than i thought. opened:
https://github.com/monome/aleph/issues/269

**Pull request merged**
