### PR TITLE
Many Changes (lines timebase, CKDIV, LINLIN, revert cv, fix slews, &c)

### PR DESCRIPTION
**Pull request by boqs**
Another pretty hectic changeset here - but *think* I finally have a lines which can handle my beatslicing looper patch without randomly exploding.

CV is untested.

I believe these two changes unlocked the weird 'action at a distance' I was observing mid-synthspew:
https://github.com/boqs/aleph/commit/21777c08d27dd39459e0a1b98f6a2b8ebc237c4b
https://github.com/boqs/aleph/commit/d1c51a419745cf5dab948c9d1b5b6322473970e5

I may experiment more with this change:
https://github.com/monome/aleph/commit/505d3b49d01e87eb28cdffd1e3bae4520a5f7e2b

I don't believe this change will cause any practical degradation of sound quality:
https://github.com/boqs/aleph/blob/lines_timebase/modules/lines/lines.c#L132-L176
But I'm struggling to judge whether the extra mixing bitdepth is snake oil or not...

### CODE REVIEW

**Comment by boqs** [comment]
there's also a couple of easier bits hiding in the midst of the chaos:
BEES LINLIN improvement:
https://github.com/monome/aleph/pull/301/commits/3b6eb07100f63f461b82a4fa8c5f54771ae8a009

hugely useful new feature for TIMER:
https://github.com/monome/aleph/pull/301/commits/c4e21e9aa2a1658f5ffbb50016ea68260348af67

Weird in that I can't fully get my head round the radix implementation but heavily tested:
https://github.com/monome/aleph/pull/301/commits/6e7220621cbc7de5cf9d6b000bd16f0493551a7a

**Comment by boqs** [comment]
Frustratingly, this still isn't quite there.  It's optimised enough to not explode on param changes with a single line, but working with two simultaneous lines can tip cpu limit over the edge...

**Comment by boqs** [comment]
I believe this is now ready to merge.  Lines passes stress tests with the new fade-in/fade-out for write head feature.

**Comment by boqs** [comment]
Was starting to feel a bit like the boy who cried wolf with this PR but I just updated again & I'm as certain as I can be this time that it's ready to rock.

- repeated lines stress test, passed
- quickly checked lines, waves, fmsynth, dsyn, acid all behave as expected after initial boot
- quickly loaded up & tested the modified BEES operators

And sorry for the gratuitious line-noise today.  Was really pushing myself to the limit to finally get 0.8.0 out the door - as usual concise, clear communication went out the window (sigh)!

**Comment by catfact** [comment]
ok lets do it

**Pull request merged**
