### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by electropourlaction**

### CODE REVIEW

**Comment by electropourlaction** [comment]
.

**Comment by electropourlaction** [comment]
oops!

**Comment by electropourlaction** [comment]
did not want this to happen, can I just close this and that will not cause any trouble?

**Comment by ghost** [comment]
Hey, yeah we can just close this pull-request (assuming you definitely don't want to merge these changes).

Kind of curious about progress off on your branch - getting audio from SDcard to/fro bfin would be a good feature if I want to build 4 track tape app, or hack around with a performance sampler BEES module.

also have quite a bit of my own work that may be ready to merge into 'official' mainline and needs reviewing...

We should put our heads together in the not-too-distant future to try and get all our combined work building against the 'main' aleph dev branch.  Otherwise things will get too disparate!

But, for example, the hacked svf code on my dev branch might work for you in your work tree - dunno how far we've diverged, but seem to remember it's months/years since the last merge!

**Pull request closed without merging**
