### PR TITLE
screen refresh out of TC interrupt in bees, c++/juce compatibility in bees, block processing, more 

### PR DESCRIPTION
**Pull request by catfact**
kind of a grab bag of changes, including some experiments that haven't worked out yet, and some unfinished but promising things, and finally a few things that seem useful.
- in bees, moved screen refresh out of the TC interrupt (can't believe it was in there.) this seems to make other timed events a little smoother. the tradeoff is that if the event queue is filling up, the screen can get  first partially and then completely stuck. i think it's a good trade; at least it's an immediate indicator of what is happening. @rick-monster had some thoughts about changing the way we handle a full event queue, which seemed worth pursuing.
- started a JUCE-based graphical bees editor. pretty early stages but some tricky compilation steps and graphics context management is worked out. hoping for contributors, otherwise it will take a while to get finished.
- relatedly, all bees headers now have `__cplusplus` switches, and avr32_sim sources compile again, and will even link with g++.
- fix a minor bug with op_gate not pickling/unpickling its inputs.
- fix a potential bug where count of graphics ops could underflow and totally screw things up (not sure if it ever happened.)
- some more incremental tweaks to block processing on bfin - control changes can continue to be collected during an audio block, and are processed at the end of it.
- tried implementing a cycle counter on the bfin, and added SPI protocol code and a bees operator to retreive CPU usage back to the avr32.  but it doesn't work; for some reason reading the CYCLES registers totally stalls parameter change handling. very mysterious. would be nice to figure this out.
- cleaned out a _lot_ of dead code, comment, and print_dbg cruft. of course there is plenty more still floating around.

### CODE REVIEW

**Comment by ghost** [comment]
Hmm  - I got interested in the event queue because all the serial-overload bees crash states I've seen seem to spew event queue-full errors, even after the overloading serial comms stimulus is removed.  Maybe the change to move screen refresh out of interrupt prevents serial-overload crash already?  Will test at home.

One other possibility is that bees simply cannot recover from a totally full event queue.  Thinking one way to test this is rig some op or other with an event-queue-flooding payload (also experiment with different _types_ of events for the payload), send the booby-trapped op a single bang, and see if the system subsequently recovers...

**Comment by catfact** [comment]
well, when events are being raised faster than they are processed, eventually nothing will happen until something slows down (a soft timer or peripheral.)

what i was thinking of was your suggestion that the event queue should be emptied instead of saturated. i tried this at once point a long time ago and can't really remember how it worked out - certainly the effects were unpredictable. but it might be more recoverable. i would definitely want to accompany some really obvious UI thing, like immediately flashing the whole screen white or something, so the user is warned that stuff isn't necessarily going to make sense until something is throttled.

**Comment by ghost** [comment]
What you're saying does make a lot of sense.  _Theoretically_ I would expect UI to get a bit intermittent & buggy under those overload conditions, but more or less keep on trucking even if some button-presses or screen-redraws get dropped.

However allowing the event queue circular buffer to wrap (effectively completely draining it from full) didn't actually prevent outright crash due to serial overload. Interesting problem - maybe b0761f7 provides a missing piece of the puzzle...

**Comment by ghost** [comment]
26c2e47 looks like a bunch of DOS line-endings leaked into files that were previously using UNIX convention.  this means I can't merge my changes to param.c into a local copy of catfact/dev .  Can we look at that before merging these commits?

**Comment by catfact** [comment]
huh! yes of course... sorry about that

**Comment by catfact** [comment]
ok i blasted the whole tree with dos2unix and i have no problems merging.. does it work for you?

**Comment by ghost** [comment]
that's one way to skin this particular cat I guess - kind of uneasy about it gimme a sec maybe I can squish out the mistake and retain the commit history...

**Comment by ghost** [comment]
can't untangle the mess with rebase magic - but able to merge both my active branches into local copy of your dev (after the dos2unix commit) - just testing if anything's broken now...

EDIT: bfin module emulator build broken after the merge - once I fix that & re-test the serial comms we can merge this...

**Comment by catfact** [comment]
i have no problem closing this request and redoing (26c2e47fcf2a426e538645f8926e7403020b6ef2), the big one that seems to have introduced CRs. 

dos2unix only got a few bees sources:
apps/bees/src/op.h                                                                                                |   408 ++---
 apps/bees/src/ops/op_add.c                                                                                        |   180 +-
 apps/bees/src/param.c                                                                                             |   436 ++---
 apps/bees/src/scene.c                                                                                             |   848 ++++-----
 apps/bees/src/util.h                                                                                              |   116 +-

and a great many things from 3-rd party code (libfixmath, fat_io_lib, and juce)

**Comment by ghost** [comment]
ok other than the CR thing all ok to merge.  Only 2 trivial changes required to fix emulator build.  Serial overload still triggering hard crash (no more so than on the unmerged feature branch) - only difference is we now have the 'white screen of death'.  I'm going to try the event-queue-bomb-payload thing see if that also triggers the crash...

**Comment by catfact** [comment]
how weird, i can't get a crash at all now with timers, even with several running at 1ms. i suppose serial interrupts could be coming in at >1khz though. it clearly isn't a good idea to do this though, or expect that the avr32 can keep up with that many interrupts and keep all the timers going. 

if a large-throughput transactoin is required, seems mandatory to pause app processing (i.e., disable timer IRQs) until it is done. have you tried that yet?

**Comment by ghost** [comment]
nope haven't tried it - let's have a look around for the right incantation...

**Pull request closed without merging**
