### PR TITLE
(re-do of #254) screen refresh event (with WSOD), beekeep_juce, block process tweaks

### PR DESCRIPTION
**Pull request by catfact**
the last try added some DOS line endings to bees sources. this reverses those, but leaves files that previously had DOS lines untouched (namely `libfixmath`, `fat_io_lib`, and some other 3rd-party ones.) did convert line endings to unix in JUCE code.

---

kind of a grab bag of changes, including some experiments that haven't worked out yet, and some unfinished but promising things, and finally a few things that seem useful.
- in bees, moved screen refresh out of the TC interrupt (can't believe it was in there.) this seems to make other timed events a little smoother. the tradeoff is that if the event queue is filling up, the screen can get  first partially and then completely stuck. i think it's a good trade; at least it's an immediate indicator of what is happening. @rick-monster had some thoughts about changing the way we handle a full event queue, which seemed worth pursuing.
- started a JUCE-based graphical bees editor. pretty early stages but some tricky compilation steps and graphics context management is worked out. hoping for contributors, otherwise it will take a while to get finished.
- relatedly, all bees headers now have `__cplusplus` switches, and avr32_sim sources compile again, and will even link with g++.
- fix a minor bug with op_gate not pickling/unpickling its inputs.
- fix a potential bug where count of graphics ops could underflow and totally screw things up (not sure if it ever happened.)
- some more incremental tweaks to block processing on bfin - control changes can continue to be collected during an audio block, and are processed at the end of it.
- tried implementing a cycle counter on the bfin, and added SPI protocol code and a bees operator to retreive CPU usage back to the avr32.  but it doesn't work; for some reason reading the CYCLES registers totally stalls parameter change handling. very mysterious. would be nice to figure this out.
- cleaned out a _lot_ of dead code, comment, and print_dbg cruft. of course there is plenty more still floating around.

### CODE REVIEW

**Comment by catfact** [comment]
NB: (@rick-monster especially) i did a forced push to catfact/dev, so might want to re-clone any copies of this fork.

**Comment by ghost** [comment]
All looks good to me now!

**Comment by catfact** [comment]
will go ahead and bring this in then in case anyone wants to work with it.

**Comment by catfact** [comment]
the-addams-family-pilot-season-one-9-18-64-the-addams-family-was-based-on-the-characters-in-charles-addams-new-yorker-cartoons

**Comment by ghost** [comment]
ook!? hairier than thou

**Comment by rick** [comment]
:shipit: :+1: :ghost: :skull:

**Pull request merged**
