### PR TITLE
skektek

### PR DESCRIPTION
**Pull request by catfact**
# don't merge, don't try to build, just ignore this for now

in-progress PR to merge the many fixes and features from the `skektek` branch

will be applying ~140 patches a few at a time, so this could take a while.

### CODE REVIEW

**Comment by lazzarello** [comment]
as of 1194bde942b42d49382a0bb3923e6410be9a5025 I'm building all the DSP modules. The build for `modules/mix` fails at link time with the following message

```
bfin-elf-gcc -mcpu=bf533 -T mix.lds \
	 ../../bfin_lib/obj/control.o  ../../bfin_lib/obj/cv.o  ../../bfin_lib/obj/init.o  ../../bfin_lib/obj/isr.o  ../../bfin_lib/obj/main.o  ../../bfin_lib/obj/spi.o  ../../bfin_lib/obj/util.o \
	mix.o ../../dsp/filter_1p.o  \
	-o mix \
	-lm -lbfdsp -lbffastfp
/opt/uClinux/bfin-elf/bfin-elf/bin/ld.real: error: no memory region specified for loadable section `.text'
collect2: ld returned 1 exit status
make: *** [mix] Error 1
```

**Comment by lazzarello** [comment]
Also looks like there are some function definitions that conflict with an included header in `modules/pitchtoy`

```
bfin-elf-gcc -Wall -mcpu=bf533 -I../../bfin_lib/src/ -I../../bfin_lib/src//libfixmath -I../../bfin_lib//../common -I../../bfin_lib//../dsp -I./ -03 -D ARCH_BFIN=1 -c -o pitchtoy.o pitchtoy.c -mcpu=bf533
pitchtoy.c: In function ‘module_init’:
pitchtoy.c:140: warning: passing argument 2 of ‘pitchShift_init’ discards qualifiers from pointer target type
pitchtoy.c:141: warning: passing argument 2 of ‘pitchShift_init’ discards qualifiers from pointer target type
pitchtoy.c:142: warning: passing argument 2 of ‘pitchShift_init’ discards qualifiers from pointer target type
pitchtoy.c:143: warning: passing argument 2 of ‘pitchShift_init’ discards qualifiers from pointer target type
pitchtoy.c:174:1: warning: "simple_slew" redefined
In file included from ../../bfin_lib//../dsp/echoTap.h:18,
                 from ../../bfin_lib//../dsp/pitch_shift.h:15,
                 from pitchtoy.c:28:
../../bfin_lib//../dsp/ricks_tricks.h:110:1: warning: this is the location of the previous definition
pitchtoy.c: At top level:
pitchtoy.c:214: error: redefinition of ‘mix_aux_mono’
../../bfin_lib//../dsp/ricks_tricks.h:12: error: previous definition of ‘mix_aux_mono’ was here
pitchtoy.c:220: error: redefinition of ‘mix_panned_mono’
../../bfin_lib//../dsp/ricks_tricks.h:17: error: previous definition of ‘mix_panned_mono’ was here
make: *** [pitchtoy.o] Error 1
```

**Comment by catfact** [comment]
yeah i'm just focused on getting the merge clean, i don't expect every build target to work at every step.
PR is just here to keep track of progress across multiple machines, since none of us have a lot of time to dedicate

if you want to help with the merge i can send you the patch files but probably helps to be very familiar with the codebase

**Comment by lazzarello** [comment]
I'm scared  :)  I did get the avr32 stuff to build and it's running so that's cool.

**Comment by catfact** [comment]
the ultimate goal of this PR is to get upstream syncd with the skektek version for which you already have snapshot

**Comment by catfact** [comment]
the ultimate goal of this PR is to get upstream syncd with the skektek version for which you already have snapshot

**Pull request closed without merging**
